### ISSUE TITLE
create a readme file for my portfolio

### ISSUE THREAD

**Issue by Yashpsct010** [Yashpsct010/PortFolio#1]

**Comment by Spandanahm172** [comment]
Hi, can you please assign this issue to me!

**Comment by Yashpsct010** [comment]
@Spandanahm172  ok

**Comment by Spandanahm172** [comment]
@Yashpsct010 can you provide me information about what you need in the portfolio.

Thank you!

**Comment by Yashpsct010** [comment]
@Spandanahm172 I want a simple readme file for my portfolio 
1.Prerequisites
2.Built With
3.Installation
4.Contact
5.Separate buttons if possible
